name: Deploy STAGING

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to STAGING via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 171.22.24.45
          username: root
          key: ${{ secrets.SMARTTRADER_STG_SSH_KEY }}
          script: |
            cd /root/smart-trader-stg
            ./deploy-stg.sh
